### PR TITLE
Merge 0.4.1 from testing to master

### PR DESCRIPTION
**Pull request by MayeulC**
## Problem

- Outdated master branch

## Solution

- Merge testing

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [x] (WIP) The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by MayeulC** [comment]
!testme

**Comment by MayeulC** [comment]
Weird CI error, looks like synapse was not installed, I relaunched it.

Confirmed working on my system, but it only worked after I installed an updated signald, and restarted both mautrix_signal and signald: https://github.com/YunoHost-Apps/mautrix_signal_ynh/issues/22#issuecomment-1293730996

**Comment by nathanael-h** [comment]
Confirm upgrade from master (0.3.0) works on my server. I did not had the signald upgrade issue.

**Comment by Gredin67** [comment]
!testme
Should be merged ASAP because all bridges are broken #64 because of https://gitlab.com/signald/signald/-/issues/343

**Comment by Thatoo** [comment]
!testme

**Comment by MayeulC** [comment]
Merged as suggested by @Gredin67 :)

**Pull request merged**
