### PR TITLE
Upgrade mautrix-signal to v0.3.0

### PR DESCRIPTION
**Pull request by MayeulC**
## Problem
- Upstream mautrix-signal release

## Solution
- Upgrade dependency

## PR Status
- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [X] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_signal_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by MayeulC** [comment]
!testme

**Comment by MayeulC** [comment]
Hmm, besides Synapse falling to install in the CI, an issue might be that upstream is removing support for python 3.7 https://github.com/mautrix/signal/commit/c92d4f1818462b66a73ab57ea1bc063e4514be30 (yes, it's a typo in the commit title).

**Comment by Gredin67** [comment]
!bullseyetestme

**Comment by MayeulC** [comment]
It might need rebasing on #45 before...

**Comment by Gredin67** [comment]
@MayeulC how about taking over the Maintainer status in manifest.json ?
As yunohost bullseye will soon be released, we could push bullseye to the testing branch. I just created a buster branch from the testing branch

**Comment by MayeulC** [comment]
I think we should add some checks to fail the upgrade on buster before merging this into testing or master.

I haven't upgraded my yunohost to bullseye yet, I'm not sure about the maintainer status. I imagine I can, but I would prefer to co-maintain it, especially as I won't have much time until the end of July. Going further, I am not sure if I will keep using Yunohost for my Matrix infrastructure (I am not sure of anything yet).

**Pull request merged**
