### PR TITLE
`!signal` instead of `!sg` and remove `admin and `domain` option in manifest

### PR DESCRIPTION
**Pull request by Thatoo**
## Problem

`!sg` has been replaced by `!signal` and  `admin and `domain` don't seem to be viable option settings to mention in manifest.toml (I got inspiration for the rewrite from the mautrix_whatsapp app)

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by nathanael-h** [comment]
Hello, the PR looks good. Just a small question about the change from `!sg` to `!signal`, does it work also with upgrade? I assume that this value is read from the config.yaml file by the app at the runtime, but I did not test it myself, did you?

**Comment by nathanael-h** [comment]
!testme

**Comment by Thatoo** [comment]
> Hello, the PR looks good. Just a small question about the change from `!sg` to `!signal`, does it work also with upgrade? I assume that this value is read from the config.yaml file by the app at the runtime, but I did not test it myself, did you?

After update we need to use `!signal` instead of `!sg`.

**Comment by nathanael-h** [comment]
!testme

**Pull request merged**
