### PR TITLE
Config panel permissions

### PR DESCRIPTION
**Pull request by Gredin67**
## Problem

- Changes on Permissions in config panel not saved at upgrade

## Solution

- Initialize permission lists at install and upgrade
- Save them in `ynh_app_setting_set` as tags (comma separated list in a string)  `"value1,value2"`

### CODE REVIEW

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
@thardev could you adapt your `sed` magic for `permissions` to https://github.com/mautrix/signal/blob/master/mautrix_signal/example-config.yaml#L282-L284 
In whatsapp (go) bridges:
```
    permissions:
        "*": relay
        "example.com": user
        "@admin:example.com": admin
```
in python bridges
```
    permissions:
        "*": "relay"
        "example.com": "user"
        "@admin:example.com": "admin"
```

**Comment by MayeulC** [comment]
@Gredin67, I don't really see a difference. You don't need to quote simple strings like these in YAML.

The only issue I have is (and I don't know if it's the same issue upstream, but that's certainly an issue when reading/writing the config for ynh helpers) that you can't have the same user in multiple sections, as it's a dictionary, and not a list.

For instance: the following won't work:

```yaml
permissions:
   "*": relay
   "*": user
```

Or:

```yaml
permissions:
   "@admin:matrix.org": admin
   "@admin:matrix.org": user
```

**Comment by Gredin67** [comment]
closing to re-open against #70

**Pull request closed without merging**
