### PR TITLE
Bullseye and v0.3.0

### PR DESCRIPTION
**Pull request by Gredin67**
## Solution
- *Fix package check for https://github.com/YunoHost-Apps/synapse_ynh/commit/e5f93690dbe93df22217e5c2b5f209c63f46931c*
- *Apply last example_ynh*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_signal_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by Gredin67** [comment]
!testme

**Comment by MayeulC** [comment]
If I understand correctly, this drops support for Buster in v3.0? (This will effectively drop buster altogether).

I suggest we create a "buster" branch on GitHub with the latest version that works on buster, even if we don't really maintain it.

**Comment by Gredin67** [comment]
@nathanael-h can you confirm the issue you had with this branch? At upgrade or at fresh install? I would wait on your feedback before merging.

**Comment by nathanael-h** [comment]
Hi, sorrry for the delay @Gredin67 I just upgraded from 0.2.3 to 0.3.0 using testing branch. 

Testing was on this commit [91165d6](https://github.com/YunoHost-Apps/mautrix_signal_ynh/commit/91165d6ac4f52a72a6b30b19d24aef4ab28a4806)

The bridge is running as expect. I am running on Debain11 :rocket:  
LGTM

**Comment by yalh76** [comment]
!testme

**Pull request merged**
