### PR TITLE
Upgrade to v0.2.1

### PR DESCRIPTION
**Pull request by nathanael-h**
## Problem
- A new version is available

## Solution
- Upgrade :smiley: 
- Ok on my server

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_signal_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by nathanael-h** [comment]
Hello @Gredin67 or @MayeulC could you trigger the CI and review ?

**Comment by MayeulC** [comment]
Hello nathanael! Thanks for the PR!

I will review, but I can't trigger the CI. I asked for the rights in the appropriate channel some time ago, but didn't get feedback.

Please note that this will still not upgrade signald #22 , probably due to a bug in yunohost's helper scripts. If you run signald < 0.15.0-27 I suggest you manually install it from the release deb at https://updates.signald.org/pool/main/s/signald/signald_0.15.0-27-88722d97_amd64.deb :)

**Comment by nathanael-h** [comment]
Ok thank for details about signald, and the review. Could we merge this and deal with signald upgrade in another PR ? Or is this mandatory ?

**Comment by nathanael-h** [comment]
In fact I am running this version: `signald 0.15.0-27-88722d97`
Maybe I have it since I used the  PR https://github.com/YunoHost-Apps/mautrix_signal_ynh/pull/28#issuecomment-979870861

**Comment by nathanael-h** [comment]
!testme

**Comment by MayeulC** [comment]
> Could we merge this and deal with signald upgrade in another PR

That's the plan.

I'm not sure what the merging policy is. I will merge into testing, then merge to master in a few days.

Thanks for triggering the CI, and giving me the rights :)

**Pull request merged**
